### ISSUE TITLE
Flash with links show as a escaped string when redirect

### ISSUE THREAD

**Issue by erickcsh** [pboling/cacheable-flash#36]
In the following example some action calls the `before_filter_that_redirects`  this assigns a flash message that has a link and redirects to show. Then show assigns other flash message with another link (to google in this example). When they are shown the `:error` message shows as `<a href="www.facebook.com">Message</a>` while the `:notice` message shows as `Google` with a working link
```
def show
  flash[:notice] = "#{view_context.link_to "Google", "www.google.com"}".html_safe
end

def before_filter_that_redirects
  flash[:error] = "#{view_context.link_to "Message", "www.facebook.com"}".html_safe
  redirect_to show_path
end
```

**Comment by pboling** [comment]
Interesting.  I just looked at the source, and it appears that it should only be escaping if the string is not marked html safe.  So I am puzzled by this.  If you want to open the gem up and find the line number where the bad escaping happens, it would help me a lot, otherwise I'll get to it when I can.  This gem isn't very actively maintained anymore, due to lack of time on my part (and Pivotal handed it off to me a long time ago).
